#include "DShader.h"

#include <iostream>
#include <dxcapi.h>

#include "IO/IOManager.h"
#include "Graphics/DXUtils.h"


using namespace DeltaEngine;
using namespace Microsoft::WRL;

DShader::DShader()
    : m_vertexShaderBlob(nullptr)
    , m_pixelShaderBlob(nullptr)
    , m_sourcePath(L"")
    , m_vertexShaderEntryPoint(L"")
    , m_pixelShaderEntryPoint(L"")
    , m_vertexShaderTargetProfile(L"")
    , m_pixelShaderTargetProfile(L"")
{

}

DeltaEngine::DShader::~DShader()
{
    //if (m_vertexShaderBlob)
    //{
    //    m_vertexShaderBlob->Release();
    //}

    //if (m_pixelShaderBlob)
    //{
    //    m_pixelShaderBlob->Release();
    //}
}

void DeltaEngine::DShader::SetSourcePath(const std::wstring& sourcePath)
{
    m_sourcePath = sourcePath;
    CompileShader();
}

void DeltaEngine::DShader::SetVertexShaderEntryPoint(const std::wstring& entryPoint)
{
    m_vertexShaderEntryPoint = entryPoint;
    CompileShader();
}

void DeltaEngine::DShader::SetPixelShaderEntryPoint(const std::wstring& entryPoint)
{
    m_pixelShaderEntryPoint = entryPoint;
    CompileShader();
}

void DeltaEngine::DShader::SetVertexShaderTargetProfile(const std::wstring& targetProfile)
{
    m_vertexShaderTargetProfile = targetProfile;
    CompileShader();
}

void DeltaEngine::DShader::SetPixelShaderTargetProfile(const std::wstring& targetProfile)
{
    m_pixelShaderTargetProfile = targetProfile;
    CompileShader();
}

void DeltaEngine::DShader::SetInputLayout(const std::vector<D3D12_INPUT_ELEMENT_DESC>& inputLayout)
{
    m_inputLayout = inputLayout;
}

void DShader::CompileShader()
{
    ComPtr<IDxcUtils> dxcUtils;
    ComPtr<IDxcCompiler3> compiler;
    ComPtr<IDxcIncludeHandler> includeHandler;
    ThrowIfFailed(DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(&compiler)));
    ThrowIfFailed(DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(&dxcUtils)));
    ThrowIfFailed(dxcUtils->CreateDefaultIncludeHandler(&includeHandler));

    std::wstring shaderPath = IOManager::GetEngineSourceAssetFullPath(m_sourcePath);
    ComPtr<IDxcBlobEncoding> sourceBlob;
    ThrowIfFailed(dxcUtils->LoadFile(shaderPath.c_str(), nullptr, &sourceBlob));

    BOOL known;
    UINT32 encoding;
    ThrowIfFailed(sourceBlob->GetEncoding(&known, &encoding));
    DxcBuffer sourceBuffer { .Ptr = sourceBlob->GetBufferPointer(), .Size = sourceBlob->GetBufferSize(), .Encoding = encoding };

    // Vertex shader
    LPCWSTR pszArgs[] = {
        shaderPath.c_str(), // Optional shader source file name for error reporting
                          // and for PIX shader source view.
        L"-E", m_vertexShaderEntryPoint.c_str(), // Entry point.
        L"-T", m_vertexShaderTargetProfile.c_str(), // Target.
        L"-Zi", // Enable debug information
        //L"-D", L"MYDEFINE=1", // A single define.
        //L"-Fo", L"myshader.bin", // Optional. Stored in the pdb.
        L"-Fd", L"./", // The file name of the pdb. This must either be supplied
                                 // or the autogenerated file name must be used.
        //L"-Fd", L"myshader.pdb",
        //L"-Qstrip_reflect", // Strip reflection into a separate blob.
    };
    //ComPtr<IDxcCompilerArgs> arguments;
    //ThrowIfFailed(dxcUtils->BuildArguments(shaderPath.c_str(), m_vertexShaderEntryPoint.c_str(), m_vertexShaderTargetProfile.c_str(), nullptr, 0, nullptr, 0, &arguments));
    ComPtr<IDxcResult> vsResult;
    ThrowIfFailed(compiler->Compile(&sourceBuffer, pszArgs, _countof(pszArgs), includeHandler.Get(), IID_PPV_ARGS(&vsResult)));
    HRESULT hr;
    ThrowIfFailed(vsResult->GetStatus(&hr));
    if (FAILED(hr))
    {
        ComPtr<IDxcBlobEncoding> error;
        vsResult->GetErrorBuffer(&error);
        std::string errorMessage(static_cast<const char*>(error->GetBufferPointer()), error->GetBufferSize());
        std::cerr << errorMessage << std::endl;
    }

    vsResult->GetResult(&m_vertexShaderBlob);

    ComPtr<IDxcBlob> pPDB = nullptr;
    ComPtr<IDxcBlobUtf16> pPDBName = nullptr;
    vsResult->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
    {
        FILE* fp = NULL;

        // Note that if you don't specify -Fd, a pdb name will be automatically generated.
        // Use this file name to save the pdb so that PIX can find it quickly.
        _wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
        fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
        fclose(fp);
    }


    // Pixel shader
    LPCWSTR pszPixelArgs[] = {
        shaderPath.c_str(), // Optional shader source file name for error reporting
                            // and for PIX shader source view.
        L"-E", m_pixelShaderEntryPoint.c_str(), // Entry point.
        L"-T", m_pixelShaderTargetProfile.c_str(), // Target.
        L"-Zi", // Enable debug information
        // L"-D", L"MYDEFINE=1", // A single define.
        // L"-Fo", L"myshader.bin", // Optional. Stored in the pdb.
         L"-Fd", L"./", // The file name of the pdb. This must either be supplied
        //  or the autogenerated file name must be used.
        //L"-Fd", L"myshader.pdb",
        // L"-Qstrip_reflect", // Strip reflection into a separate blob.
    };

    //ComPtr<IDxcCompilerArgs> arguments;
    //ThrowIfFailed(dxcUtils->BuildArguments(shaderPath.c_str(), m_pixelShaderEntryPoint.c_str(), m_pixelShaderTargetProfile.c_str(), nullptr, 0, nullptr, 0, &arguments));
    ComPtr<IDxcResult> psResult;
    compiler->Compile(&sourceBuffer, pszPixelArgs, _countof(pszPixelArgs), includeHandler.Get(), IID_PPV_ARGS(&psResult));
    psResult->GetStatus(&hr);
    if (FAILED(hr))
    {
        ComPtr<IDxcBlobEncoding> error;
        psResult->GetErrorBuffer(&error);
        std::string errorMessage(static_cast<const char*>(error->GetBufferPointer()), error->GetBufferSize());
        std::cerr << errorMessage << std::endl;
    }

    psResult->GetResult(&m_pixelShaderBlob);

    psResult->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
    {
        FILE* fp = NULL;
    
        // Note that if you don't specify -Fd, a pdb name will be automatically generated.
        // Use this file name to save the pdb so that PIX can find it quickly.
        _wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
        fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
        fclose(fp);
    }
}
