#pragma once


// Common macros for the Delta Engine
#define DELTA_ENGINE_NS_BEGIN namespace DeltaEngine {
#define DELTA_ENGINE_NS_END }


// DLL export/import macros
#ifdef _WIN32
    #ifdef DELTAENGINE_EXPORTS
        #define DELTAENGINE_API __declspec(dllexport)
    #else
        #define DELTAENGINE_API __declspec(dllimport)
    #endif
#else
    #define DELTAENGINE_API __attribute__((visibility("default")))
#endif


// Reflection macros
#define DCLASS(...)
#define DSTRUCT(...)
#define DFUNCTION(...)
#define DPROPERTY(...)
#define DGENERATED_BODY(ClassName) \
    friend class DeltaEngine::Reflection::Private::ReflectionRegister_##ClassName; \
    \
public: \
    DClass* GetClass() const override \
    { \
        return GetReflectionRegistry().FindClassByName(#ClassName); \
    }

#define DGENERATED_BODY_STRUCT(StructName) \
    friend class DeltaEngine::Reflection::Private::ReflectionRegister_##StructName;


// Dynamic delegate macros (definitions generated by DeltaHeaderTool)
#define DECLARE_DYNAMIC_DELEGATE(DelegateName) \
    class DelegateName : public DeltaEngine::FDynamicDelegate \
    { \
    public: \
        DELTAENGINE_API void Execute() const; \
    };

#define DECLARE_DYNAMIC_DELEGATE_OneParam(DelegateName, Param1Type, Param1Name) \
    class DelegateName : public DeltaEngine::FDynamicDelegate \
    { \
    public: \
        DELTAENGINE_API void Execute(Param1Type Param1Name) const; \
    };

#define DECLARE_DYNAMIC_DELEGATE_TwoParams(DelegateName, Param1Type, Param1Name, Param2Type, Param2Name) \
    class DelegateName : public DeltaEngine::FDynamicDelegate \
    { \
    public: \
        DELTAENGINE_API void Execute(Param1Type Param1Name, Param2Type Param2Name) const; \
    };

#define DECLARE_DYNAMIC_MULTICAST_DELEGATE(DelegateName) \
    class DelegateName : public DeltaEngine::FDynamicMulticastDelegate \
    { \
    };

#define DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(DelegateName, Param1Type, Param1Name) \
    class DelegateName : public DeltaEngine::FDynamicMulticastDelegate \
    { \
    public: \
        DELTAENGINE_API void Broadcast(Param1Type Param1Name) const; \
    };

#define DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(DelegateName, Param1Type, Param1Name, Param2Type, Param2Name) \
    class DelegateName : public DeltaEngine::FDynamicMulticastDelegate \
    { \
    public: \
        DELTAENGINE_API void Broadcast(Param1Type Param1Name, Param2Type Param2Name) const; \
    };
