"""DeltaHeaderTool — C++ reflection code generator for DeltaEngine."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from parser import parse_header
from generator import generate_header, generate_source


def _contains_dclass(path: Path) -> bool:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.lstrip()
            if stripped.startswith("#"):
                continue
            if "DCLASS(" in stripped:
                return True
        return False
    except OSError:
        return False


def _is_up_to_date(source: Path, out_h: Path, out_cpp: Path) -> bool:
    if not out_h.exists() or not out_cpp.exists():
        return False
    src_mtime = source.stat().st_mtime
    return (
        out_h.stat().st_mtime >= src_mtime
        and out_cpp.stat().st_mtime >= src_mtime
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="DeltaHeaderTool")
    ap.add_argument("--input-dir", required=True, type=Path)
    ap.add_argument("--output-dir", required=True, type=Path)
    ap.add_argument("--manifest", required=True, type=Path)
    ap.add_argument("--engine-root", required=True, type=Path)
    ap.add_argument("--include-dir", action="append", default=[], type=Path)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    input_dir: Path = args.engine_root / args.input_dir
    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    headers = sorted(input_dir.rglob("*.h"))

    reflected_stems: set[str] = set()
    generated_cpps: list[Path] = []

    for header in headers:
        stem = header.stem

        if not _contains_dclass(header):
            continue

        reflected_stems.add(stem)

        out_h = output_dir / f"{stem}.generated.h"
        out_cpp = output_dir / f"{stem}.generated.cpp"

        if not args.force and _is_up_to_date(header, out_h, out_cpp):
            generated_cpps.append(out_cpp)
            print(f"  up-to-date: {stem}")
            continue

        print(f"  generating: {stem}")

        classes = parse_header(header, input_dir, args.include_dir)

        if not classes:
            print(f"  WARNING: {header.name} contains DCLASS( but no "
                  "reflected classes were found by libclang", file=sys.stderr)
            continue

        header_text = ""
        source_text = ""
        for cls in classes:
            header_text += generate_header(cls)
            source_text += generate_source(cls)

        out_h.write_text(header_text, encoding="utf-8", newline="\n")
        out_cpp.write_text(source_text, encoding="utf-8", newline="\n")
        generated_cpps.append(out_cpp)

    # ── stale file cleanup ────────────────────────────────────
    for f in sorted(output_dir.iterdir()):
        if f.suffix not in (".h", ".cpp"):
            continue
        raw_stem = f.stem
        if raw_stem.endswith(".generated"):
            raw_stem = raw_stem[: -len(".generated")]
        if raw_stem not in reflected_stems:
            f.unlink()
            print(f"  removed stale: {f.name}")

    # ── write manifest ────────────────────────────────────────
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    lines = ['# AUTO-GENERATED by DeltaHeaderTool - DO NOT EDIT\n']
    lines.append('set(DELTA_GENERATED_SOURCES\n')
    for cpp in sorted(generated_cpps):
        lines.append(f'    "{cpp.resolve().as_posix()}"\n')
    lines.append(')\n')
    args.manifest.write_text("".join(lines), encoding="utf-8", newline="\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
