#include "Runtime/Logging/LogChannels.h"

DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogCore);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogReflection);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogSerialization);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogAsset);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogRenderer);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogShader);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogRHI);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogPostProcess);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogShadow);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogIO);
DEFINE_LOG_CATEGORY_API(DELTAENGINE_API, LogEngine);
