#include "Runtime/Logging/LogChannels.h"

DELTA_ENGINE_NS_BEGIN

DEFINE_LOG_CATEGORY(LogCore)
DEFINE_LOG_CATEGORY(LogReflection)
DEFINE_LOG_CATEGORY(LogSerialization)
DEFINE_LOG_CATEGORY(LogAsset)
DEFINE_LOG_CATEGORY(LogRenderer)
DEFINE_LOG_CATEGORY(LogShader)
DEFINE_LOG_CATEGORY(LogRHI)
DEFINE_LOG_CATEGORY(LogPostProcess)
DEFINE_LOG_CATEGORY(LogShadow)
DEFINE_LOG_CATEGORY(LogIO)
DEFINE_LOG_CATEGORY(LogEngine)

DELTA_ENGINE_NS_END
