#pragma once

#include "LogCategory.h"

DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogCore);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogReflection);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogSerialization);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogAsset);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogRenderer);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogShader);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogRHI);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogPostProcess);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogShadow);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogIO);
DECLARE_LOG_CATEGORY_API(DELTAENGINE_API, LogEngine);
