#pragma once
#include "EngineIncludes.h"

// Includes from source header


DELTA_ENGINE_NS_BEGIN

// Forward declarations (auto-generated by DeltaHeaderTool)
class SimpleReflectClass;


namespace Reflection {
namespace Private {

struct SimpleReflectClass_DoSomething_Params
{
    float x;
};

class ReflectionRegister_SimpleReflectClass
{
public:
    static void ReflectionRegisterFn_SimpleReflectClass();
};

} // namespace Private
} // namespace Reflection

template <>
DELTAENGINE_API SimpleReflectClass* CreateDObject<SimpleReflectClass>();
DELTA_ENGINE_NS_END
